#pragma once

#include "ddraw-testing.h"

#define LOG_TEST_RESULT(TestID, LogEntry, TestValue, ExpectedResult) \
	{ \
		DWORD Value = (DWORD)TestValue; \
		DWORD Result = (DWORD)ExpectedResult; \
		if (Value == Result && Value != TEST_FAILED && Result != TEST_FAILED) \
		{ \
				Logging::Log() << "Testing: " << TestID << " Succeded! " << LogEntry << TestValue << " -> " << ExpectedResult; \
		} \
		else \
		{ \
				Logging::Log() << "Testing: " << TestID << " FAILED! " << LogEntry << TestValue << " -> " << ExpectedResult; \
		} \
	}

constexpr DWORD vDDraw1 = 0;
constexpr DWORD vDDraw2 = 1;
constexpr DWORD vDDraw3 = 2;
constexpr DWORD vDDraw4 = 3;
constexpr DWORD vDDraw7 = 4;
constexpr DWORD vDDraw7Ex = 5;

constexpr DWORD TEST_FAILED = (DWORD)-1;

struct TESTMATRIX {
	DWORD TestID;
	DWORD Result[6];
};

constexpr TESTMATRIX TestResults[] = {
	// IDirectDraw
	{ 100, { 1, 1, 1, 1, 1, 1 } },
	{ 101, { 2, 1, (DWORD)E_NOINTERFACE, 1, 1, 2 } },
	{ 102, { 2, 1, 0, 1, 1, 2 } },
	{ 103, { 1, 0, 0, 0, 0, 1 } },
	{ 104, { 1, 1, 0, 1, 1, 1 } },
	{ 105, { 0, 0, 0, 0, 0, 0 } },
	{ 106, { 0, 0, 0, 0, 0, 0 } },

	// IDirectDrawSurface
	{ 200, { 1, 1, 1, 1, 1, 1 } },
	{ 201, { 1, 1, 1, 2, 2, 2 } },
	{ 202, { 1, 1, 1, 1, 1, 1 } },
	{ 203, { 1, 1, 1, 3, 3, 4 } },
	{ 204, { 1, 1, 1, 2, 2, 2 } },
	{ 205, { 1, 1, 1, 1, 1, 1 } },
	{ 210, { 2, 1, 1, 1, 1, 1 } },
	{ 211, { 1, 2, 1, 1, 1, 1 } },
	{ 212, { 1, 1, 2, 1, 1, 1 } },
	{ 213, { 1, 1, 1, 2, 1, 1 } },
	{ 214, { 1, 1, 1, 1, 2, 2 } },
	{ 215, { 2, 1, 1, 1, 1, 1 } },
	{ 216, { 1, 2, 1, 1, 1, 1 } },
	{ 217, { 1, 1, 2, 1, 1, 1 } },
	{ 218, { 1, 1, 1, 2, 1, 1 } },
	{ 219, { 1, 1, 1, 1, 2, 2 } },
	{ 220, { 1, 1, 1, 2, 2, 2 } },
	{ 221, { 1, 1, 1, 2, 2, 2 } },
	{ 222, { 1, 1, 1, 2, 2, 2 } },
	{ 223, { 1, 1, 1, 2, 2, 2 } },
	{ 224, { 1, 1, 1, 2, 2, 2 } },

	// IDirect3DTexture
	{ 300, { 2, 2, 2, 2, 2, (DWORD)E_NOINTERFACE } },
	{ 301, { 2, 2, 2, 2, 2, 0 } },
	{ 302, { 1, 1, 1, 3, 3, 0 } },
	{ 303, { 3, 3, 3, 3, 3, 0 } },
	{ 304, { 3, 3, 3, 3, 3, 0 } },
	{ 305, { 1, 1, 1, 3, 3, 0 } },
	{ 306, { 3, 3, 3, 3, 3, 0 } },
	{ 307, { 3, 3, 3, 3, 3, 0 } },
	{ 308, { 1, 1, 1, 3, 3, 0 } },
	{ 309, { 3, 3, 3, 3, 3, 0 } },
	{ 310, { 3, 3, 3, 3, 3, 0 } },
	{ 311, { 3, 3, 3, 3, 3, 0 } },
	{ 312, { 1, 1, 1, 3, 3, 0 } },
	{ 313, { 4, 4, 4, 4, 4, 0 } },
	{ 314, { 4, 4, 4, 4, 4, 0 } },
	{ 315, { 4, 4, 4, 4, 4, 0 } },
	{ 316, { 1, 1, 1, 3, 3, 0 } },

	// IDirectDrawGammaControl
	{ 400, { 1, 1, 1, 1, 1, 1 } },
	{ 401, { 1, 1, 1, 1, 1, 1 } },
	{ 402, { 1, 1, 1, 2, 2, 2 } },
	{ 403, { (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE } },
	{ 405, { 1, 1, 1, 1, 1, 1 } },
	{ 406, { 1, 1, 1, 1, 1, 1 } },
	{ 407, { 1, 1, 1, 3, 3, 4 } },
	{ 408, { (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE } },
	{ 410, { 1, 1, 1, 1, 1, 1 } },
	{ 411, { 2, 2, 1, 1, 1, 1 } },
	{ 412, { 1, 1, 1, 2, 2, 2 } },
	{ 413, { (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE } },
	{ 415, { 1, 1, 1, 1, 1, 1 } },
	{ 416, { 1, 1, 1, 1, 1, 1 } },
	{ 417, { 1, 1, 1, 2, 2, 2 } },
	{ 418, { (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE } },
	{ 420, { 1, 1, 1, 1, 1, 1 } },
	{ 421, { 1, 1, 1, 1, 1, 1 } },
	{ 422, { 1, 1, 1, 2, 2, 2 } },
	{ 423, { (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE } },
	{ 425, { 1, 1, 1, 1, 1, 1 } },
	{ 426, { 1, 1, 1, 2, 1, 1 } },
	{ 427, { 1, 1, 1, 2, 2, 2 } },
	{ 428, { (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE } },
	{ 430, { 1, 1, 1, 1, 1, 1 } },
	{ 431, { 1, 1, 1, 1, 2, 2 } },
	{ 432, { 1, 1, 1, 2, 2, 2 } },
	{ 433, { (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE } },

	// IDirect3D
	{ 500, { 2, 2, 2, 2, (DWORD)E_NOINTERFACE, 2 } },
	{ 501, { 2, 2, 2, 2, 2, 2 } },
	{ 502, { 3, 3, 3, 3, 3, 3 } },
	{ 503, { 3, 3, 3, 3, 3, 3 } },
	{ 504, { 3, 3, 3, 3, 3, 3 } },
	{ 505, { 3, 3, 3, 3, 3, 3 } },

	// All interfaces quried by IDirectDraw
	{ 1000, { 2, 1, (DWORD)E_NOINTERFACE, 1, 1, 1 } },
	{ 1001, { 2, 1, (DWORD)E_NOINTERFACE, 1, 1, 1 } },
	{ 1002, { 2, 1, (DWORD)E_NOINTERFACE, 1, 1, 1 } },
	{ 1003, { 1, 2, (DWORD)E_NOINTERFACE, 1, 1, 1 } },
	{ 1004, { 1, 2, (DWORD)E_NOINTERFACE, 1, 1, 1 } },
	{ 1005, { 1, 2, (DWORD)E_NOINTERFACE, 1, 1, 1 } },
	{ 1006, { (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE } },
	{ 1009, { 1, 1, (DWORD)E_NOINTERFACE, 2, 1, 1 } },
	{ 1010, { 1, 1, (DWORD)E_NOINTERFACE, 2, 1, 1 } },
	{ 1011, { 1, 1, (DWORD)E_NOINTERFACE, 2, 1, 1 } },
	{ 1012, { 1, 1, (DWORD)E_NOINTERFACE, 1, 2, 2 } },
	{ 1013, { 1, 1, (DWORD)E_NOINTERFACE, 1, 2, 2 } },
	{ 1014, { 1, 1, (DWORD)E_NOINTERFACE, 1, 2, 2 } },
	{ 1015, { (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE } },
	{ 1018, { (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE } },
	{ 1021, { (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE } },
	{ 1024, { (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE } },
	{ 1027, { (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE } },
	{ 1030, { (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE } },
	{ 1033, { (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE } },
	{ 1036, { (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE } },
	{ 1039, { (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE } },
	{ 1042, { 2, 2, (DWORD)E_NOINTERFACE, 2, 2, (DWORD)E_NOINTERFACE } },
	{ 1043, { 2, 2, (DWORD)E_NOINTERFACE, 2, 2, (DWORD)E_NOINTERFACE } },
	{ 1044, { 2, 2, (DWORD)E_NOINTERFACE, 2, 2, (DWORD)E_NOINTERFACE } },
	{ 1045, { 2, 2, (DWORD)E_NOINTERFACE, 2, 2, (DWORD)E_NOINTERFACE } },
	{ 1046, { 2, 2, (DWORD)E_NOINTERFACE, 2, 2, (DWORD)E_NOINTERFACE } },
	{ 1047, { 2, 2, (DWORD)E_NOINTERFACE, 2, 2, (DWORD)E_NOINTERFACE } },
	{ 1048, { 2, 2, (DWORD)E_NOINTERFACE, 2, 2, (DWORD)E_NOINTERFACE } },
	{ 1049, { 2, 2, (DWORD)E_NOINTERFACE, 2, 2, (DWORD)E_NOINTERFACE } },
	{ 1050, { 2, 2, (DWORD)E_NOINTERFACE, 2, 2, (DWORD)E_NOINTERFACE } },
	{ 1051, { (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, 2 } },
	{ 1052, { (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, 2 } },
	{ 1053, { (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, 2 } },
	{ 1054, { (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE } },
	{ 1057, { (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE } },
	{ 1060, { (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE } },
	{ 1063, { (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE } },
	{ 1066, { (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE } },
	{ 1069, { (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE } },
	{ 1072, { (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE } },
	{ 1075, { (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE } },
	{ 1078, { (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE } },
	{ 1081, { (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE } },
	{ 1084, { (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE } },
	{ 1087, { (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE } },
	{ 1090, { (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE } },
	{ 1093, { (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE } },
	{ 1096, { (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE } },
	{ 1099, { (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE, (DWORD)E_NOINTERFACE } },
};

template <typename DDType>
static DWORD GetResults(DWORD TestID)
{
	static DWORD ArrayLoc =
		std::is_same_v<DDType, IDirectDraw> ? vDDraw1 :
		std::is_same_v<DDType, IDirectDraw2> ? vDDraw2 :
		std::is_same_v<DDType, IDirectDraw3> ? vDDraw3 :
		std::is_same_v<DDType, IDirectDraw4> ? vDDraw4 :
		std::is_same_v<DDType, IDirectDraw7> ? vDDraw7 :
		std::is_same_v<DDType, IDirectDraw7Ex> ? vDDraw7Ex : TEST_FAILED;
	if (ArrayLoc == TEST_FAILED)
	{
		return TEST_FAILED;
	}

	for (const TESTMATRIX& entry : TestResults)
	{
		if (entry.TestID == TestID)
		{
			return entry.Result[ArrayLoc];
		}
	}

	return TEST_FAILED;
}
